---
- name: create admin group
  group: name=admin state=present

- name: create users
  user: >
    name={{ item.name }}
    groups=sudo,docker
    shell=/bin/bash
    password={{ item.password }}
  with_items: users

- name: set authorized keys
  authorized_key: >
    user='{{ item.name }}'
    key='{{lookup('file', item.public_key)}}'
  with_items: users
